package errors

func Handle(err error) {
	// todo
}
